### ISSUE TITLE
"Unable to render page, Try increasing timeout" 

### ISSUE THREAD

**Issue by Moondra** [meetmangukiya/instagram-scraper#7]
I've installed all the dependencies and trying to run it via the command line like this:
    python3.6 instagram_scraper.py --tags  billfish --count 10

However, I'm getting the following error:

`Traceback (most recent call last):
  File "instagram_scraper.py", line 101, in <module>
    main(args.tags, args.count)
  File "instagram_scraper.py", line 89, in main
    _single_tag_processing(tag, total_count)
  File "instagram_scraper.py", line 70, in _single_tag_processing
    tag, total_count)):
  File "instagram_scraper.py", line 34, in scrape_instagram_tag
    req.html.render(scrolldown=page)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests_html.py", line 590, in render
    raise MaxRetries("Unable to render the page. Try increasing timeout")
requests_html.MaxRetries: Unable to render the page. Try increasing timeout`

Any ideas? 

Thank you.

**Comment by meetmangukiya** [comment]
It's probably because it was not able to fetch and render in the given timeout, maybe some issue with the internet connection or low speed.

**Comment by Moondra** [comment]
I don't seem to have a problem with internet speed (My other scraper with muli-threading works fine) Could it be some other reason?  Thank you.
